name: Test and Lint DPF Utils

on:
  push:
    branches:
      - main
    paths:
      - 'dpf-utils/**'
      - '.github/workflows/test-dpf-utils.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'dpf-utils/**'
      - '.github/workflows/test-dpf-utils.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      
      - name: Run tests
        run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      
      - name: Run linter
        run: make lint

